Add controllers - correct visible synchronization
Alexey-Sutyrin/java-shareit pull request #2
Opened 2024-03-31 23:38 UTC by Alexey-Sutyrin

Add controllers - correct visible synchronization
Old try was declined, due to "main" branch incorrectly filled.
Now "main" returned to basic stance, starting Pull request with "add-controllers" branch.

2024-04-01 08:24 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public Map<String, String> handleUserValidationException(UserValidationException e) {
Вместо обезличенного `Map<String, String>` лучше создать свой классик например ErrorResponse и возвращать его.

2024-04-01 08:27 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserController(UserService userService) {
` @Autowired` перед конструктором не обязательно писать, и без этой аннотации в текущей версии спринга сработает

2024-04-01 08:28 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/User.java
>  public class User {
для единообразия этот класс поместить в пакет model

2024-04-01 08:29 UTC, VadimZharkov requested changes
Можно улучшить

2024-04-01 14:44 UTC, Alexey-Sutyrin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserController(UserService userService) {
@Autowired убрал, спасибо.

2024-04-01 15:03 UTC, Alexey-Sutyrin commented on src/main/java/ru/practicum/shareit/user/User.java
>  public class User {
Сделал пакет model, чтобы структура раздела User была аналогична разделу Item, спасибо, так реально красивее!

2024-04-02 06:13 UTC, VadimZharkov approved these changes

2024-04-02 06:25 UTC, merged

2024-04-02 06:25 UTC, Alexey-Sutyrin commented
Sprint 13 - approved, merged.