Sprint 14 - add - bookings - Iteration 1
Alexey-Sutyrin/java-shareit pull request #3
Opened 2024-04-02 19:33 UTC by Alexey-Sutyrin

2024-04-03 06:04 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<BookingOutDto> findBookingsOfUser(@RequestParam(defaultValue = "ALL", required = false) String state,
defaultValue = "ALL", required = false противоречат друг другу, т.к. дефолтное значение будет всегда

2024-04-03 08:13 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +        for (Booking booking : bookings) {
со stream().map().collectToList посовременней будет выглядеть

2024-04-03 08:16 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public Map<String, String> handleUserValidationException(UserValidationException e) {
Зачем на мапу вернул не понятно.

2024-04-03 08:18 UTC, VadimZharkov requested changes
Можно улучшить

2024-04-03 18:49 UTC, Alexey-Sutyrin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<BookingOutDto> findBookingsOfUser(@RequestParam(defaultValue = "ALL", required = false) String state,
взаимоисключающие пункты поправил, required = false убрал, спасибо!

2024-04-03 19:13 UTC, Alexey-Sutyrin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +        for (Booking booking : bookings) {
Исправил, спасибо!

2024-04-03 21:15 UTC, Alexey-Sutyrin commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public Map<String, String> handleUserValidationException(UserValidationException e) {
Вернул обратно проверки ErrorResponse, очень долго воевал с Postman, прошу понять и простить.

2024-04-04 09:03 UTC, VadimZharkov approved these changes

2024-04-04 12:56 UTC, Alexey-Sutyrin commented
14 sprint - add-bookings - approved, merged

2024-04-04 12:57 UTC, merged