Sprint 15 - add-item-requests - Iteration
Alexey-Sutyrin/java-shareit pull request #4
Opened 2024-04-04 22:23 UTC by Alexey-Sutyrin

Sprint 15 - add-item-requests - Iteration

2024-04-04 22:36 UTC, Alexey-Sutyrin commented
Вынужденно вернусь к варианту Map в Error Handler, он значительно стабильнее в использовании.

2024-04-05 07:19 UTC, VadimZharkov requested changes
Нужно добавить тесты для входящих dto с помощью аннотации `@JsonTest`

2024-04-06 06:10 UTC, Alexey-Sutyrin commented
Тесты DTO добавил.

2024-04-07 06:12 UTC, VadimZharkov approved these changes

2024-04-07 15:06 UTC, Alexey-Sutyrin commented
Sprint 15 approved - add-item-requests merged to main

2024-04-07 15:06 UTC, merged