Sprint 16 - ShareIt - add-docker - Iteration
Alexey-Sutyrin/java-shareit pull request #5
Opened 2024-04-08 06:42 UTC by Alexey-Sutyrin

Sprint 16 - ShareIt - add-docker - Iteration 1 - gateway and server mod

2024-04-09 06:51 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +}
Нужно добавить 
	@ResponseStatus(HttpStatus.BAD_REQUEST)
	public ErrorResponse handleMethodArgumentNotValidException(MethodArgumentNotValidException e) 
это исключение возникнет на аннотации типа @PozitiveOrZero

и также 
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(Throwable e)

для всех оставшихся

2024-04-09 06:53 UTC, VadimZharkov requested changes
Можно улучшить

2024-04-09 21:01 UTC, Alexey-Sutyrin commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +}
Спасибо, скорректировал.

2024-04-10 06:50 UTC, VadimZharkov approved these changes

2024-04-10 09:09 UTC, Alexey-Sutyrin commented
Sprint 16 approved

2024-04-10 09:09 UTC, merged